name: Yigit K. Guc
favicon: null
layout_spectrum: 0.88751
typography_spectrum: 0.74434
title: 'An Artist working on audio & visual arts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#8bb3cd'
    - '#dee7f2'
    - '#0b1627'
    - '#6a99b7'
    - '#465367'
  brandStrength: 0.25
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
