name: Yigit K. Guc
favicon: null
layout_spectrum: 0.88751
typography_spectrum: 0.74434
title: 'An Artist working on audio & visual arts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5625
  lightness: 0.5625
  saturation: 0.8125
  rhythmicContrast: 0.5
purpose: []
