name: Yigit K. Guc
favicon: null
layout_spectrum: 0.9695196191314608
typography_spectrum: 0.07989604538306594
title: 'An Artist working on audio & visual arts'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.19202699465677142
  lightness: 0.7416447557043284
  saturation: 0.00806116103194654
  rhythmicContrast: 0.4257856239564717
purpose: []
